version: '3.8'

services:
  app:
    image: dockerurlshorterapi
    ports:
      - 9999:9999
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env