version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USERNAME= postgres
      - POSTGRES_PASSWORD= pass
      - POSTGRES_DB= urlShorterDb
    ports:
      - "5432:5432"
