version: '3.8'

services:
  app:
    image: dockerurlshorterapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:alpine
    container_name: ${DB_NAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env