version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: urlshorterdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: urlshorterdb
      POSTGRES_USER: ${DB_USERNAME:test}
      POSTGRES_PASSWORD: ${DB_PASSWORD:test}