version: '3.8'

services:
  app:
    image: dockerurlshorterapi
    ports:
      - 9999:9999
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/urlshorterdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: urlshorterdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: urlshorterdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test