version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: urlshorterdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: urlshorterdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    links:
      - redis
  redis:
    image: redis
    ports:
      - "5433:5433"