name: Java CI

on:
  pull_request:
    branches:
      - master

jobs:
  dockerImage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --platform linux/amd64 --tag issue-metrics:"$(date +%s)"
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Create jar
        run: ./gradlew jar

      - name: Start Docker Compose services
        run: docker compose -f docker-compose.yml up -d

      - name: Run test
        run: ./gradlew test -i
